### ISSUE TITLE
Mobile devices do not connect with this

### ISSUE THREAD

**Issue by LuizGyro** [zwometer/Godot4MultiplayerMVP#1]
Hello!

I'm sorry if this is the wrong place to contact you regarding this project.
I've been experimenting with the code you've posted to get a grip on Godot's online capabilities. I've managed to connect PCs from multiple different networks to the server, but mobile phones have been giving me some trouble.

For further details of my setup, I have one PC in my network, of which I made the IP static (in my router's settings), and I've fowarded the 49664 port (so, any TCP/UDP connections coming from any IP on port 49664 are listened by my fixed IP's PC on the same port). I also put this IP for DMZ on my router's settings. Then, I use no-IP to fix a name for my public IP, and that port (49664) and this name ("name".ddns.net)  is what I pass as arguments on both the client and server code.
This setup works for two PCs on separate networks, considering one of them is my PC (running the server code) on my own network. If a PC in a different network tries to connect using the client's code, it connects just fine. If I try to connect from another PC on my own network using the client's code, it does NOT connect.

As I've said before in the introduction, the real issue lies in mobile connections. It never connects when I deploy using regular one-click deploy, but it works when I deploy with remote debug. I don't understand this behaviour specifically.
If anyone could shed some light on it, i'd be very grateful.

If any more information is needed, I'll be happy to provide it.

I apologize if this is not the place for this, and I'll gladly delete this issue if it is not appropriate.

Thank you for you attention.

**Comment by zwometer** [comment]
Hey, thanks for the feedback!
I haven't tested mobile connections yet but I'm planning to do so "sometime in the future" (lots of other stuff on my plate right now). 
For now I have no idea, what the problem could be. 
If you or anyone else get more insights into this problem, please share.

**Comment by LuizGyro** [comment]
Thanks for the reply!
I'll be trying to make it work over here. If I get any new insights, I'll be sure to keep you posted.
Thanks again! :)

**Comment by LuizGyro** [comment]
I got it!
For it to work on mobile, you have to set some permissions on the export (at least for Android). Namely, "Internet" and "Change Network State".
